package cmd

import (
	"context"
	"fmt"
	"shai/internal/parser"
	"shai/internal/prompt"
	"shai/internal/provider"
	"strings"

	"github.com/spf13/cobra"
)

// runQuery is the main execution path for the shai assistant.
// It handles translating the natural language query into a shell command.
func runQuery(cmd *cobra.Command, args []string) error {
	ctx := context.Background()
	query := strings.Join(args, " ")

	providerName, _ := cmd.Flags().GetString("provider")
	if providerName == "" {
		providerName = cfg.Active.Provider
	}
	if providerName == "" {
		return fmt.Errorf("no provider configured. Use 'shai config set-provider' or --provider flag")
	}

	modelOverride, _ := cmd.Flags().GetString("model")
	shellOverride, _ := cmd.Flags().GetString("shell")

	// 1. Build prompts
	sysPrompt, err := prompt.BuildSystemPrompt(shellOverride)
	if err != nil {
		return fmt.Errorf("failed to build system prompt: %w", err)
	}

	messages := []provider.Message{
		{Role: "system", Content: sysPrompt},
		{Role: "user", Content: query},
	}

	// 2. Initialize provider
	p, err := provider.NewProvider(ctx, providerName, *cfg, modelOverride)
	if err != nil {
		return err
	}

	// 3. LLM Completion Loop (Tool use not fully implemented yet)
	resp, err := p.Complete(ctx, provider.CompletionRequest{
		Messages: messages,
	})
	if err != nil {
		return fmt.Errorf("LLM completion failed: %w", err)
	}

	// 4. Parse response
	parsed, err := parser.Parse(resp.Content)
	if err != nil {
		return fmt.Errorf("failed to parse LLM response: %w", err)
	}

	// 5. Display explanation
	noExplain, _ := cmd.Flags().GetBool("no-explain")
	if !noExplain {
		for _, line := range parsed.Explanation {
			fmt.Printf("# %s\n", line)
		}
	}

	// 6. Output command (Injection not implemented yet, just print for now)
	dryRun, _ := cmd.Flags().GetBool("dry-run")
	if dryRun || parsed.Command == "" {
		if parsed.Command != "" {
			fmt.Printf("> %s\n", parsed.Command)
		} else {
			fmt.Println("No command generated by LLM.")
		}
	} else {
		// For now, we print it as if it's staged
		fmt.Printf("> %s", parsed.Command)
		// To make it look like a prompt buffer, we might need to avoid a newline at the end
		// but since we aren't doing real injection yet, we'll just print it.
		fmt.Println()
	}

	return nil
}
