package cmd

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ameb8/shai/internal/agent"
	"github.com/ameb8/shai/internal/parser"
	"github.com/ameb8/shai/internal/prompt"
	"github.com/ameb8/shai/internal/provider"

	"github.com/spf13/cobra"
)

// runQuery executes the core agent loop to translate a user's natural language
// request into a shell command. It manages prompt construction, provider
// interaction, and output formatting.
func runQuery(cmd *cobra.Command, args []string) error {
	ctx := context.Background()
	query := strings.Join(args, " ")

	// Resolve the AI provider from flags or global configuration.
	providerName, _ := cmd.Flags().GetString("provider")
	if providerName == "" {
		providerName = cfg.Active.Provider
	}
	if providerName == "" {
		return fmt.Errorf("no provider configured. Use 'shai config set-provider' or --provider flag")
	}

	modelOverride, _ := cmd.Flags().GetString("model")
	shellOverride, _ := cmd.Flags().GetString("shell")

	// Prepare the system instructions and initial message history.
	sysPrompt, err := prompt.BuildSystemPrompt(shellOverride)
	if err != nil {
		return fmt.Errorf("failed to build system prompt: %w", err)
	}

	messages := []provider.Message{
		{Role: "system", Content: sysPrompt},
		{Role: "user", Content: query},
	}

	// Initialize the requested AI provider with the active configuration.
	p, err := provider.NewProvider(ctx, providerName, *cfg, modelOverride)
	if err != nil {
		return err
	}

	// Execute the completion loop, allowing the agent to use tools if necessary.
	resp, err := agent.Complete(ctx, p, messages)
	if err != nil {
		return fmt.Errorf("LLM completion failed: %w", err)
	}

	// Extract the final shell command and explanation from the LLM response.
	parsed, err := parser.Parse(resp.Content)
	if err != nil {
		return fmt.Errorf("failed to parse LLM response: %w", err)
	}

	// Print the AI's explanation as shell comments for user review.
	noExplain, _ := cmd.Flags().GetBool("no-explain")
	if !noExplain {
		for _, line := range parsed.Explanation {
			fmt.Printf("# %s\n", line)
		}
	}

	// Persist the generated command to a file if requested for shell integration.
	cmdFile, _ := cmd.Flags().GetString("cmd-file")
	dryRun, _ := cmd.Flags().GetBool("dry-run")

	if cmdFile != "" && parsed.Command != "" && !dryRun {
		dir := filepath.Dir(cmdFile)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory for cmd-file: %w", err)
		}
		if err := os.WriteFile(cmdFile, []byte(parsed.Command), 0644); err != nil {
			return fmt.Errorf("failed to write command to file: %w", err)
		}
	}

	// Output the command directly to the terminal when not writing to a file or in dry-run mode.
	if cmdFile == "" || dryRun {
		if parsed.Command != "" {
			fmt.Printf("> %s\n", parsed.Command)
		} else if dryRun {
			fmt.Println("No command generated by LLM.")
		}
	}

	return nil
}
